plugins {
    id "com.android.application"
    id "kotlin-android"
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.gridlayout:gridlayout:1.1.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation "androidx.core:core-ktx:1.16.0"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2'
}

repositories {
    mavenCentral()
    google()
}

allprojects {
    tasks.withType(JavaCompile).tap {
        configureEach {
            options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
        }
    }
}

kotlin {
    jvmToolchain(8)
}

android {
    namespace "de.hu_berlin.informatik.spws2014.mapever"
    signingConfigs {
        config {
        }
    }
    compileSdk = 36
    namespace = "de.hu_berlin.informatik.spws2014.mapever"
    buildTypes {
        debug {
            applicationIdSuffix ".debug"
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'
            shrinkResources = true
            signingConfig = signingConfigs.config
        }
    }
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }

        // Move the build types to build-types/<type>
        // For instance, build-types/debug/java, build-types/debug/AndroidManifest.xml, ...
        // This moves them out of them default location under src/<type>/... which would
        // conflict with src/ being used by the main source set.
        // Adding new build types or product flavors should be accompanied
        // by a similar customization.
        debug.setRoot('build-types/debug')
        release.setRoot('build-types/release')
    }
    defaultConfig {
        applicationId 'de.reimardoeffinger.mapever'
        targetSdkVersion 36
        signingConfig = signingConfigs.config
        resourceConfigurations += ['de', 'en', 'fr', 'sv']
        minSdkVersion 21
    }
    buildFeatures {
        buildConfig = true
    }
    productFlavors {
    }
}
